export const FETCH_RESTAURANTS_LOADING = '[APP] FETCH RESTAURANTS LOADING';
export const FETCH_RESTAURANTS_SUCCESS = '[APP] FETCH RESTAURANTS SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = '[APP] FETCH RESTAURANTS FAILURE';