export const FETCH_RESTAURANTS_LOADING = '[APP] FETCH RESTAURANTS LOADING';
export const FETCH_RESTAURANTS_SUCCESS = '[APP] FETCH RESTAURANTS SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = '[APP] FETCH RESTAURANTS FAILURE';

export const FETCH_RESTAURANT_DETAILS_LOADING = '[APP] FETCH RESTAURANT DETAILS LOADING';
export const FETCH_RESTAURANT_DETAILS_SUCCESS = '[APP] FETCH RESTAURANT DETAILS SUCCESS';
export const FETCH_RESTAURANT_DETAILS_FAILURE = '[APP] FETCH RESTAURANT DETAILS FAILURE';